name = "AnotherMyPackage"
uuid = "f1c66aff-a09d-42d5-b8f0-aaee6da1ff2d"
authors = ["Onoda <onoda.k.829@ms.saitama-u.ac.jp>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
LinearAlgebra = "1.11.0"
Revise = "3.7.6"
